### ISSUE TITLE
How do you generate the JWT secrets for .env file?

### ISSUE THREAD

**Issue by songproducer** [StakeNow/SIWT#3]
Hello, I would like to implement Tezos sign in on my Mastodon server. The documentation at https://jwt.io was not clear how to generate a secret

**Comment by jdsika** [comment]
To my knowledge you can use a pw generator or face palm on your keyboard as long as the secret is sufficiently long

**Comment by royscheeren** [comment]
Hi @songproducer @jdsika is correct, although I wouldn't recommend face palming on your keyboard, you may choose the secret. Just treat it like a password. 

If you need any support please reach out on our Discord https://discord.com/invite/6J3bjhkpxm. We're happy to help and we'd love to see what you build!
