### ISSUE TITLE
SIWT Discord Bot: User Feedback

### ISSUE THREAD

**Issue by dansan566** [StakeNow/SIWT#4]
_Just tried it out from the native app in OSX. Everything seemed to work as desired. Only problem IMHO is that after signing with my tezos wallet on siwt.xyz in Discord, I don't get a confirmation on my own. so I went out of the verification channel, back in and clicked verify again. then I got the reply "you are verified"._

**Comment by jdsika** [comment]
That is the same as in #2 but a good confirmation.

**Comment by dansan566** [comment]
I will close the issue because of #2
